#Greenfoot properties. Settings in this file override "bluej.defs" and "greenfoot.defs"
#Sat Sep 12 12:47:39 CEST 2026
bluej.debugger.x=16
bluej.debugger.y=16
bluej.editor.fontsize=12
bluej.editor.stride.sidebarShowing=true
bluej.openPackage1=E\:\\PROJECT\\group project
bluej.recentProject0=E\:\\PROJECT\\group project
bluej.terminal.x=16
bluej.terminal.y=16
greenfoot.uid=8c77b8c7-6ed8-4e61-af9e-1cd92df22d8b
session.numeditors.java=0
session.numeditors.stride=0
